site_name: Bpy Gallery

nav:
  - Home: index.md
  - Getting Started: n0getting_started.md
  - Objects: n1objects.ipynb
  - Use of Python Packages: n2install_uninstall.ipynb
  - Databpy 1: n3databpy1.ipynb
  - Databpy 2: n3databpy2.ipynb
  - Typst: n4typst_examples.ipynb


theme:
  name: material
  features:
    # - navigation.instant
    # - navigation.tracking
    # - content.code.copy
  palette:
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition

plugins:
  - search:
      separator: '[\s\-_,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - mkdocs-jupyter